#include QMK_KEYBOARD_H
#include "keymap_extras/keymap_japanese.h"

enum combos {
  LSCLN_COLN,
  JK_HENK,
  DF_MHEN,
  OP_MINS
};

const uint16_t PROGMEM lscln_combo[] = {KC_L, KC_SCLN, COMBO_END};
const uint16_t PROGMEM jk_combo[] = {KC_J, KC_K, COMBO_END};
const uint16_t PROGMEM df_combo[] = {KC_D, KC_F, COMBO_END};
const uint16_t PROGMEM op_combo[] = {KC_O, KC_P, COMBO_END};

combo_t key_combos[] = {
  [LSCLN_COLN] = COMBO(lscln_combo, JP_COLN),
  [JK_HENK] = COMBO(jk_combo, JP_HENK),
  [DF_MHEN] = COMBO(df_combo, JP_MHEN),
  [OP_MINS] = COMBO(op_combo, KC_MINS),
};

enum layer_names {
    _DEFAULT,
    _LAYER1,
    _LAYER2,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_DEFAULT] = LAYOUT_ortho_5x12(
		KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,
		KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
		KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ENT,
		SC_LSPO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, SC_RSPC,
		KC_NO, MO(3), KC_LGUI, KC_LALT, KC_LCTL, LT(1,KC_SPC), LT(1,KC_SPC), KC_INT5, KC_NO, KC_NO, KC_RALT, KC_NO
	),
	[_LAYER1] = LAYOUT_ortho_5x12(
		KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
		KC_TRNS, LSFT(KC_1), KC_LBRC, LSFT(KC_3), LSFT(KC_4), LSFT(KC_5), KC_EQL, LSFT(KC_6), LSFT(KC_QUOT), JP_LPRN, JP_RPRN, KC_DEL,
		KC_TRNS, LSFT(KC_7), LSFT(KC_2), KC_RBRC, KC_NUHS, JP_GRV, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_QUOT, KC_TRNS,
		KC_TRNS, JP_UNDS, LSFT(KC_MINS), LSFT(KC_RBRC), LSFT(KC_NUHS), LSFT(KC_EQL), KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_INT1, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_INT4, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	),
	[_LAYER2] = LAYOUT_ortho_5x12(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_NO, KC_UP, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS,
		KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
	)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

